REASONING_V2_PROMPT_MARKER = "## EXECUTIVE_REASONING_V2"

MIN_PACKAGE_COVERAGE_FOR_EXECUTIVE_ANSWER = 60.0

SECTION_EXECUTIVE_SUMMARY = "executive_summary"
SECTION_FINDINGS = "findings"
SECTION_INTERPRETATION = "interpretation"
SECTION_RISKS = "risks"
SECTION_OPPORTUNITIES = "opportunities"
SECTION_RECOMMENDATIONS = "recommendations"
SECTION_LIMITATIONS = "limitations"
SECTION_NEXT_ANALYSES = "next_analyses"

REASONING_V2_SECTIONS: tuple[str, ...] = (
    SECTION_EXECUTIVE_SUMMARY,
    SECTION_FINDINGS,
    SECTION_INTERPRETATION,
    SECTION_RISKS,
    SECTION_OPPORTUNITIES,
    SECTION_RECOMMENDATIONS,
    SECTION_LIMITATIONS,
    SECTION_NEXT_ANALYSES,
)

HANDLED_BY_EXECUTIVE_REASONING_V2 = "executive_reasoning_v2"
