from app.domain.operations import BusinessOperation

OPERATION_SYNONYMS: dict[BusinessOperation, tuple[str, ...]] = {
    BusinessOperation.COUNT: (
        "cuantos",
        "cuántos",
        "cantidad",
        "total",
        "numero de",
        "número de",
        "existen",
        "tenemos",
        "cuenta",
        "conteo",
    ),
    BusinessOperation.SUM: (
        "total",
        "suma",
        "acumulado",
        "volumen total",
        "volumen",
        "importe total",
    ),
    BusinessOperation.AVG: (
        "promedio",
        "media",
        "promedio mensual",
        "media mensual",
    ),
    BusinessOperation.MAX: (
        "mayor",
        "máximo",
        "maximo",
        "mas alto",
        "más alto",
        "principal",
        "lider",
        "líder",
        "mejor",
        "mas alta",
        "más alta",
        "maximo movimiento",
        "máximo movimiento",
    ),
    BusinessOperation.MIN: (
        "menor",
        "mínimo",
        "minimo",
        "mas bajo",
        "más bajo",
        "peor",
        "minimo movimiento",
        "mínimo movimiento",
    ),
    BusinessOperation.TOP: (
        "quien es el principal cliente",
        "top",
        "principales",
        "mejores",
        "ranking",
        "mas importantes",
        "más importantes",
    ),
    BusinessOperation.TREND: (
        "tendencia",
        "evolucion",
        "evolución",
        "crecimiento",
        "comportamiento",
        "variacion",
        "variación",
    ),
    BusinessOperation.COMPARE: (
        "comparar",
        "comparacion",
        "comparación",
        "versus",
        "vs",
        "contrastar",
        "diferencia entre",
    ),
    BusinessOperation.LOOKUP: (
        "pertenece",
        "asociado",
        "relacionado",
        "vinculado",
        "corresponde a",
    ),
    BusinessOperation.SYSTEM_INFO: (
        "que puedes hacer",
        "que sabes hacer",
        "que puedo preguntarte",
        "capacidades",
        "funciones",
    ),
    BusinessOperation.DATA_COVERAGE: (
        "de que fecha son tus datos",
        "de que fecha son los datos",
        "hasta que fecha llegan los datos",
        "desde cuando hay informacion",
        "cual es la antiguedad de los datos",
        "cual es el rango temporal",
        "que periodo de informacion tienes",
        "periodo de los datos",
        "periodo de informacion",
        "que fechas cubren los datos",
        "fechas cubren los datos",
        "antiguedad de los datos",
        "rango temporal",
        "periodo",
        "rango de fechas",
        "fechas cubiertas",
        "fechas cubren",
        "cobertura temporal",
        "fecha minima",
        "fecha mínima",
        "fecha maxima",
        "fecha máxima",
    ),
    BusinessOperation.DATASET_INFO: (
        "que tipos de datos tienes",
        "que tipos de datos",
        "que datos analiza el asistente",
        "que informacion contiene el sistema",
        "que informacion puedo consultar",
        "que datos tienes",
        "que informacion tienes",
        "cuantos datos tienes",
        "cuántos datos tienes",
        "cuantos registros tienes",
        "cuántos registros tienes",
        "cantidad de datos",
        "volumen de datos",
        "cuantos movimientos tienes",
        "cuántos movimientos tienes",
    ),
}
