ADVISOR_PROMPT_MARKER = "## EXECUTIVE_ADVISOR_V1"
ADVISOR_MAX_ITEMS = 5

PRIORITY_ALTA = "Alta"
PRIORITY_MEDIA = "Media"
PRIORITY_BAJA = "Baja"

PRIORITY_RANK = {
    PRIORITY_ALTA: 0,
    PRIORITY_MEDIA: 1,
    PRIORITY_BAJA: 2,
}

DEFAULT_ACTION_LABEL = "Analizar"
