from enum import StrEnum


class BusinessQueryType(StrEnum):
    COUNT_CLIENTES = "COUNT_CLIENTES"
    COUNT_PROVEEDORES = "COUNT_PROVEEDORES"
    TOP_CLIENTES = "TOP_CLIENTES"
    TOP_PROVEEDORES = "TOP_PROVEEDORES"
    MAX_PROVEEDOR_MES = "MAX_PROVEEDOR_MES"
    MAX_TRANSACCION_CLIENTE = "MAX_TRANSACCION_CLIENTE"
    LOOKUP_CLIENTE_BY_CUENTA = "LOOKUP_CLIENTE_BY_CUENTA"
    SYSTEM_CAPABILITIES = "SYSTEM_CAPABILITIES"
    DATA_COVERAGE = "DATA_COVERAGE"
    DATASET_INFO = "DATASET_INFO"
    UNSUPPORTED = "UNSUPPORTED"
