from enum import StrEnum


class FallbackType(StrEnum):
    UNKNOWN = "UNKNOWN"
    AMBIGUOUS = "AMBIGUOUS"
    OUT_OF_DOMAIN = "OUT_OF_DOMAIN"
    UNSUPPORTED_CAPABILITY = "UNSUPPORTED_CAPABILITY"
    LOW_CONFIDENCE = "LOW_CONFIDENCE"
