STRATEGY_SINGLE = "SINGLE"
STRATEGY_MULTI = "MULTI"
STRATEGY_FALLBACK = "FALLBACK"

COVERAGE_FULL_THRESHOLD = 80.0
COVERAGE_PARTIAL_THRESHOLD = 60.0

CLASSIFICATION_CORRECT = "Correcto"
CLASSIFICATION_AVOIDABLE = "Evitable"
CLASSIFICATION_PARTIALLY_AVOIDABLE = "Parcialmente evitable"
CLASSIFICATION_NO_COMPATIBLE = "Sin capability compatible"
